openapi: 3.0.3
info:
  title: SCMS Validation & Claims (Java PoC)
  description: >
    Proof of Concept microservice for lottery ticket validation (win) and claim processing.
    Multi-tenancy: `customer_id` selects tenant/database; hashing algorithm per game (`games.hash_algorithm`: 1=BLAKE2b, 2=SHA-256).

servers:
  - url: http://localhost:8080
    description: Local development environment

tags:
  - name: validation
    description: Ticket validation (win)
  - name: claim
    description: Claim processing and audit logging

paths:
  /api/win/check:
    post:
      tags: [validation]
      summary: Check if a ticket is a winner (read-only)
      description: |
        Computes `ticket_hash` based on serial {YY}{GGG}{BB}{PPPPPPP}{TTT},
        uses hashing algorithm from `games.hash_algorithm` (1=BLAKE2b512, 2=SHA-256),
        then looks up in `winners` table (PK = ticket_hash).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckRequest'
            examples:
              winnerSha256:
                summary: Winning ticket
                value:
                  customer_id: "22"
                  game_id: "202"
                  batch_id: "01"
                  ticket_id: "000"
                  pack_id: "0000000"
              notWinner:
                summary: Non-winning ticket
                value:
                  customer_id: "11"
                  game_id: "101"
                  batch_id: "01"
                  ticket_id: "007"
                  pack_id: "0000123"
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckResponse'
              examples:
                found:
                  summary: Winner
                  value:
                    found: true
                    ticket_hash: "a9565fa6...0a55"
                    tier: "4"
                    claim_status: 0
                    message: null
                notFound:
                  summary: Not a winner
                  value:
                    found: false
                    ticket_hash: "eb0d90f...9939"
                    tier: null
                    claim_status: 0
                    message: "not winner"
        '400':
          description: Bad request / validation error (e.g., invalid field lengths/patterns)
          content:
            application/json:
              examples:
                found:
                  summary: Field pattern mismatch
                  value:
                    timestamp: "2026-01-15T15:32:11.406566800+01:00"
                    status: 400
                    error: "Bad Request"
                    code: "DTO_VALIDATION_ERROR"
                    message: "Invalid request fields"
                    details:
                      field_errors:
                        - field: "game_id"
                        - error: "must match \"\\d{1,3}\""
                    hint: null
                    correlation_id: "06853092-dbd8-48f1-b3e3-d9aa49a3f941"
        '500':
          description: Internal server error (unexpected)
          content:
            application/json:
              examples:
                unexpected:
                  summary: Unexpected error
                  value:
                    type: "about:blank"
                    title: "Internal Server Error"
                    status: 500
                    detail: "Unexpected exception while computing ticket hash"
                    instance: "/api/win/check"

  /api/claim:
    post:
      tags: [claim]
      summary: Update claim status (monotonic 0→1→2) and write audit log
      description: |
        Increases `ticket_claim_status` in `winners` (no decrease allowed),
        then writes one row in `claimlog` with chained signature (BLAKE2b512 = hash(payload + previous signature)).
        Works only for winning tickets.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClaimRequest'
            examples:
              increase0to1winning:
                summary: Increase from 0 → 1 (winning ticket)
                value:
                  customer_id: "22"
                  game_id: "202"
                  batch_id: "01"
                  ticket_id: "000"
                  desired_claim_value: 1
                  pack_id: "0000000"
                  f1: "channel"
                  f2: "device"
                  f3: "person"
                  f4: "external_ref"
              increase0to1notwinner:
                summary: Increase from 0 → 1 (non-winning ticket)
                value:
                  customer_id: "11"
                  game_id: "101"
                  batch_id: "01"
                  ticket_id: "007"
                  pack_id: "0000123"
                  f1: "channel"
                  f2: "device"
                  f3: "person"
                  f4: "external_ref"
                  desired_claim_value: 1
              increase1to2:
                summary: Increase from 1 → 2
                value:
                  customer_id: "22"
                  game_id: "202"
                  batch_id: "01"
                  ticket_id: "000"
                  desired_claim_value: 2
              decrease2to1:
                summary: Attempted decrease from 2 → 1 (illegal)
                value:
                  customer_id: "22"
                  game_id: "202"
                  batch_id: "01"
                  ticket_id: "000"
                  desired_claim_value: 1
      responses:
        '200':
          description: Claim update result (updated or explained no-op)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClaimResponse'
              examples:
                updated:
                  summary: Updated (e.g., 0 → 1)
                  value:
                    found: true
                    updated: true
                    ticket_hash: "a9565fa6...0a55"
                    old_claim_value: 0
                    new_claim_value: 1
                    message: null
                idempotentNoop:
                  summary: No-op (desired equals current)
                  value:
                    found: true
                    updated: false
                    ticket_hash: "a9565fa6...0a55"
                    old_claim_value: 1
                    new_claim_value: 1
                    message: null
        '400':
          description: Bad request / validation error (e.g., desired_claim_value ∉ {1,2})
          content:
            application/json:
              examples:
                badDesired:
                  summary: desired_claim_value outside allowed set
                  value:
                    timestamp: "2026-01-15T16:06:12.931819200+01:00"
                    status: 400
                    error: "Bad Request"
                    code: "DTO_VALIDATION_ERROR"
                    message: "Invalid request fields"
                    details:
                      field_errors:
                        - field: "Desired_claim_value"
                        - error: "must be less than or equal to 2"
                    hint: null
                    correlation_id: "fda0ae17-b621-49ff-9a70-28d66164a104"
        '404':
          description: Winner not found (non-existent ticket_hash / not winner) or unknown tenant/game
          content:
            application/json:
              examples:
                notWinner:
                  summary: Non-existent or not winner
                  value:
                    timestamp: "2026-01-15T16:13:27.479089900+01:00"
                    status: 404
                    error: "Not Found"
                    code: "NOT_WINNER"
                    message: "not winner"
                    details:
                      ticket_hash: "eb0d90f...9939"
                      field_errors:
                    hint: null
                    correlation_id: "d4411412-d29d-48d1-94bb-895f4f552187"
        '409':
          description: Conflict (e.g., attempt to decrease 2→1 or illegal transition)
          content:
            application/json:
              examples:
                decreaseAttempt:
                  summary: Monotonic rule violation (decrease)
                  value:
                    timestamp: "2026-01-15T16:08:37.247087600+01:00"
                    status: 409
                    error: "Conflict"
                    code: "CLAIM_DECREASE_FORBIDDEN"
                    message: "cannot decrease claim status"
                    details:
                      old_claim: 2
                      ticket_hash: "a9565fa6...0a55"
                      requested: 1
                    hint: "Only monotonic transitions allowed: 0→1→2"
                    correlation_id: "532740b0-a0bb-477e-ab28-faa1fd6c01af"
        '500':
          description: Internal server error (unexpected)
          content:
            application/json:
              examples:
                unexpected:
                  summary: Unexpected error
                  value:
                    type: "about:blank"
                    title: "Internal Server Error"
                    status: 500
                    detail: "Unexpected exception while writing audit log"
                    instance: "/api/claim"
components:
  schemas:
    CheckRequest:
      type: object
      required: [customer_id, game_id, batch_id, ticket_id]
      properties:
        customer_id:
          type: string
          description: Tenant/customer identifier (YY)
          pattern: '^\d{2}$'
          example: "11"
        game_id:
          type: string
          description: Game identifier (GGG)
          pattern: '^\d{3}$'
          example: "101"
        batch_id:
          type: string
          description: Batch identifier (BB)
          pattern: '^\d{2}$'
          example: "01"
        pack_id:
          type: string
          description: Pack identifier (PPPPPPP, optional)
          pattern: '^\d{0,7}$'
          example: "0000123"
        ticket_id:
          type: string
          description: Ticket identifier (TTT)
          pattern: '^\d{3}$'
          example: "007"

    CheckResponse:
      type: object
      properties:
        found: { type: boolean, example: true }
        ticket_hash: { type: string, example: "dbedcc2a...bce5" }
        tier: { type: string, nullable: true, example: "4" }
        prize: { type: number, format: double, nullable: true, example: 0.00 }
        claim_status: { type: integer, example: 0 }
        message: { type: string, nullable: true, example: null }

    ClaimRequest:
      allOf:
        - $ref: '#/components/schemas/CheckRequest'
        - type: object
          required: [desired_claim_value]
          properties:
            desired_claim_value:
              type: integer
              description: Target claim status (1 or 2)
              enum: [1,2]
              example: 1
            f1: { type: string, nullable: true, example: "channel" }
            f2: { type: string, nullable: true, example: "device" }
            f3: { type: string, nullable: true, example: "person" }
            f4: { type: string, nullable: true, example: "external_ref" }

    ClaimResponse:
      type: object
      properties:
        found: { type: boolean, example: true }
        updated: { type: boolean, example: true }
        ticket_hash: { type: string, example: "dbedcc2a...bce5" }
        old_claim_value: { type: integer, example: 0 }
        new_claim_value: { type: integer, example: 1 }
        message: { type: string, nullable: true, example: null }

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2026-01-15T15:32:11.406566800+01:00"
        status:
          type: integer
          example: 400
        error:
          type: string
          example: "Bad Request"
        code:
          type: string
          example: "DTO_VALIDATION_ERROR"
        message:
          type: string
          example: "Invalid request fields"
        details:
          type: object
          properties:
            field_errors:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                    example: "game_id"
                  error:
                    type: string
                    example: "must match \"\\d{1,3}\""
        hint:
          type: string
          nullable: true
          example: null
        correlation_id:
          type: string
          format: uuid
          example: "06853092-dbd8-48f1-b3e3-d9aa49a3f941"
