CREATE TABLE IF NOT EXISTS games (
  idgame INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id VARCHAR(3) UNIQUE NOT NULL,
  ticket_price DECIMAL(12,2) NOT NULL,
  hash_algorithm INT NOT NULL
);

CREATE TABLE IF NOT EXISTS winners (
  ticket_hash VARCHAR(128) PRIMARY KEY,
  game_id VARCHAR(3) NOT NULL,
  batch_id VARCHAR(2) NOT NULL,
  ticket_winning_tier_id VARCHAR(2) NOT NULL,
  ticket_claim_status INT NOT NULL DEFAULT 0,
  ticket_winning_prize NUMERIC(18,2)
);

CREATE TABLE IF NOT EXISTS claimlog (
  idclaimlog INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tx_date DATE,
  tx_time TIME,
  tx_customer_id VARCHAR(2),
  tx_game_id VARCHAR(3),
  tx_batch_id VARCHAR(2),
  tx_pack_id VARCHAR(7),
  tx_ticket_id VARCHAR(3),
  old_claim_value INT,
  new_claim_value INT,
  foreign_ref1 VARCHAR(45),
  foreign_ref2 VARCHAR(45),
  foreign_ref3 VARCHAR(45),
  foreign_ref4 VARCHAR(45),
  signature VARCHAR(128)
);


CREATE INDEX IF NOT EXISTS idx_claimlog_ticket_parts
  ON claimlog (tx_customer_id, tx_game_id, tx_batch_id, tx_pack_id, tx_ticket_id);


CREATE INDEX IF NOT EXISTS idx_claimlog_date_time
  ON claimlog (tx_date, tx_time);
